spring.application.name=demo
spring.config.import=optional:classpath:.env[.properties]
server.port=${PORT:8080}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# mysql://[DB URL]:[port]/[DB Name]?serverTimezone=UTC
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_ID}
spring.datasource.password=${DB_PW}

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

mybatis.mapper-locations=mapper/*.xml
mybatis.config-location=classpath:mybatis-config.xml
mybatis.type-aliases-package=com.example.demo.dto

# Cloudflare R2 ??
spring.cloud.aws.s3.endpoint=${CLOUD_S3_ENDPOINT:https://example.com}
spring.cloud.aws.credentials.access-key=${CLOUD_S3_ACCESSKEY}
spring.cloud.aws.credentials.secret-key=${CLOUD_S3_SECRETKEY}
spring.cloud.aws.region.static=auto
spring.cloud.aws.s3.path-style-access-enabled=true
# Bucket Name(custom name)
r2.bucket-name=${CLOUD_BUCKET_NAME}